from dotenv import load_dotenv
from app.services.google_sheets import GoogleSheetsApi
from datetime import datetime
from app.services.avito import AvitoApi, AuthRequest
from app.services.ads_sheet_processor import AvitoSheetProcessor

load_dotenv()


SHEET_ID = '1UD2CutAVHMk6M6f1brt5XVLcdwofYT6a7Hcl20dVOUA'
WORKSHEET = 'test'
WORKSHEET_ADS = 'test-2' # TODO should be generated by helper itself

CLIENT_ID = 'ergejgnrkeg'
CLIENT_SECRET = 'fh97wfr74ho'


def main():
    # import requests
    # url = "https://api.avito.ru/token"
    #
    # payload = 'client_id=AgIabqGPp6KR9GUwYWPZ&client_secret=fWYn2LQT0LfIP7nEdNlwd1-xB5_RIJTcP-hCaHyJ&grant_type=client_credentials'
    # headers = {
    #     'Content-Type': 'application/x-www-form-urlencoded'
    # }
    #
    # response = requests.request("POST", url, headers=headers, data=payload)
    #
    # print(response.text)
    processor = AvitoSheetProcessor(SHEET_ID, WORKSHEET, WORKSHEET_ADS)
    processor.execute()


if __name__ == '__main__':
    main()

